name: deploy_workflow
on:
  push:
    tags:
      - 'v*'
      
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          signoff: false
          branch: main
          base: develop
          title: '[Example] Update report'
          draft: false