name: deploy_workflow
on:
  push:
    tags:
      - 'v*'
      
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: bump-v0.0.21
          base: main
          title: '[Example] Update report'
          draft: false