name: deploy_workflow
on:
  push:
    tags:
      - 'v*'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # tag バージョンを取得する
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${{ github.ref }}

      # dev ブランチをチェックアウトする
      - name: checkout develop
        uses: actions/checkout@v2
        with:
          ref: develop

      # ブランチを作成する
      - name: Create Branch
        id: create_branch
        env:
          TZ: 'Asia/Tokyo'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=`date +"%Y%m%d"`
          TAG=${{ steps.get_version.outputs.VERSION }}
          BRANCH_NAME="release_$DATE_$TAG"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
          echo ::set-output name=branch_name::$BRANCH_NAME

      # プルリクを作成する
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          delete-branch: false
          title: '[Example] Update report ${{ steps.get_version.outputs.VERSION }}'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
